yunus
berkarcan/Bleucrm-Group-Project pull request #12
Opened 2022-03-14 17:01 UTC by yunusadl

2022-03-15 08:32 UTC, Samraskyy commented
This Cukes Runner affects other codes, so it created conflicts, need to be solved
<<<<<<< yunus
        dryRun = true,
        tags = "@yunus"
=======
        dryRun = false,
        tags = "@smoke"
>>>>>>> master
)
public class CukesRunner {

}

2022-03-16 12:47 UTC, berkarcan requested changes
fails in one step user must be hr12. And also you can add one of your test to smoke test by putting tags @BLEU-yourtestNoInJira @BLEU-759 @smoke          bleu-759 test set in jira

2022-03-16 16:10 UTC, Samraskyy approved these changes

2022-03-17 10:34 UTC, yunusadl commented
Guys could you check again? I have changed the dryRun and username and added one scenario to smoke test suite in jira, should work fine now.

2022-03-17 11:17 UTC, berkarcan approved these changes

2022-03-17 11:17 UTC, merged